apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bhavana-6/AWS-Retail-App.git
    targetRevision: dev
    path: Retail-chart
    helm:
      values: https://80E7DE0FA1D5B50B9989BCC1DA82D15E.yl4.us-east-2.eks.amazonaws.com
        userprofile:
          activeVersion: blue
  destination:
    server: 
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
