apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.label }}
spec:
  selector:
    app: {{ .Values.database.label }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
