apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: {{ .Values.service.userprofile.type }}
  selector:
    app: userprofile-{{ .Values.userprofile.activeVersion }}
  ports:
    - port: {{ .Values.userprofile.port }}
      targetPort: {{ .Values.userprofile.port }}
      protocol: TCP
