apiVersion: v1
kind: Service
metadata:
  name: userprofile-active-service
spec:
  type: {{ .Values.service.userprofile.type }}
  selector:
    app: userprofile
  ports:
    - port: {{ .Values.userprofile.port }}
      targetPort: {{ .Values.userprofile.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-preview-service
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
    - port: {{ .Values.userprofile.port }}
      targetPort: {{ .Values.userprofile.port }}
      protocol: TCP
