apiVersion: v1
kind: Secret
metadata:
  name: userprofile-secret
type: Opaque
data:
  {{ .Values.env.SESSION_SECRET }}: {{ .Values.secrets.SESSION_SECRET }}
  {{ .Values.env.EMAIL_USER }}: {{ .Values.secrets.EMAIL_USER }}
  {{ .Values.env.EMAIL_PASS }}: {{ .Values.secrets.EMAIL_PASS }}
